import path from "node:path";

export type CommentFinding = {
	line: number;
	text: string;
};

export type CommentScanOptions = {
	allowDirectives?: boolean;
	allowPatterns?: readonly RegExp[];
	knownLines?: ReadonlySet<string>;
	wholeFile?: boolean;
};

type BlockToken = readonly [string, string];

export type LanguageSyntax = {
	lineTokens: readonly string[];
	blockTokens: readonly BlockToken[];
	quotes: readonly string[];
	docstringQuotes: readonly string[];
	requireBoundary: boolean;
};

const C_FAMILY: LanguageSyntax = {
	lineTokens: ["//"],
	blockTokens: [["/*", "*/"]],
	quotes: ['"', "'", "`"],
	docstringQuotes: [],
	requireBoundary: false,
};

const HASH_FAMILY: LanguageSyntax = {
	lineTokens: ["#"],
	blockTokens: [],
	quotes: ['"', "'"],
	docstringQuotes: [],
	requireBoundary: true,
};

const PYTHON: LanguageSyntax = {
	lineTokens: ["#"],
	blockTokens: [],
	quotes: ['"', "'"],
	docstringQuotes: ['"""', "'''"],
	requireBoundary: true,
};

const DASH_FAMILY: LanguageSyntax = {
	lineTokens: ["--"],
	blockTokens: [],
	quotes: ['"', "'"],
	docstringQuotes: [],
	requireBoundary: true,
};

const LUA: LanguageSyntax = {
	lineTokens: ["--"],
	blockTokens: [["--[[", "]]"]],
	quotes: ['"', "'"],
	docstringQuotes: [],
	requireBoundary: true,
};

const MARKUP: LanguageSyntax = {
	lineTokens: [],
	blockTokens: [["<!--", "-->"]],
	quotes: [],
	docstringQuotes: [],
	requireBoundary: false,
};

const CSS: LanguageSyntax = {
	lineTokens: [],
	blockTokens: [["/*", "*/"]],
	quotes: ['"', "'"],
	docstringQuotes: [],
	requireBoundary: false,
};

const HASH_AND_C: LanguageSyntax = {
	lineTokens: ["#", "//"],
	blockTokens: [["/*", "*/"]],
	quotes: ['"', "'"],
	docstringQuotes: [],
	requireBoundary: true,
};

const EXTENSION_SYNTAX = new Map<string, LanguageSyntax>([
	[".ts", C_FAMILY],
	[".tsx", C_FAMILY],
	[".mts", C_FAMILY],
	[".cts", C_FAMILY],
	[".js", C_FAMILY],
	[".jsx", C_FAMILY],
	[".mjs", C_FAMILY],
	[".cjs", C_FAMILY],
	[".java", C_FAMILY],
	[".kt", C_FAMILY],
	[".kts", C_FAMILY],
	[".scala", C_FAMILY],
	[".swift", C_FAMILY],
	[".go", C_FAMILY],
	[".rs", C_FAMILY],
	[".c", C_FAMILY],
	[".h", C_FAMILY],
	[".cc", C_FAMILY],
	[".cpp", C_FAMILY],
	[".cxx", C_FAMILY],
	[".hpp", C_FAMILY],
	[".hh", C_FAMILY],
	[".cs", C_FAMILY],
	[".dart", C_FAMILY],
	[".groovy", C_FAMILY],
	[".gradle", C_FAMILY],
	[".proto", C_FAMILY],
	[".zig", C_FAMILY],
	[".php", HASH_AND_C],
	[".jsonc", C_FAMILY],
	[".json5", C_FAMILY],
	[".py", PYTHON],
	[".pyi", PYTHON],
	[".sh", HASH_FAMILY],
	[".bash", HASH_FAMILY],
	[".zsh", HASH_FAMILY],
	[".rb", HASH_FAMILY],
	[".pl", HASH_FAMILY],
	[".r", HASH_FAMILY],
	[".yaml", HASH_FAMILY],
	[".yml", HASH_FAMILY],
	[".toml", HASH_FAMILY],
	[".ini", HASH_FAMILY],
	[".cfg", HASH_FAMILY],
	[".conf", HASH_FAMILY],
	[".tf", HASH_AND_C],
	[".tfvars", HASH_AND_C],
	[".nix", HASH_FAMILY],
	[".sql", DASH_FAMILY],
	[".hs", DASH_FAMILY],
	[".elm", DASH_FAMILY],
	[".lua", LUA],
	[".html", MARKUP],
	[".htm", MARKUP],
	[".xml", MARKUP],
	[".svg", MARKUP],
	[".vue", MARKUP],
	[".svelte", MARKUP],
	[".md", MARKUP],
	[".mdx", MARKUP],
	[".css", CSS],
	[".scss", CSS],
	[".less", CSS],
]);

const FILENAME_SYNTAX = new Map<string, LanguageSyntax>([
	["dockerfile", HASH_FAMILY],
	["makefile", HASH_FAMILY],
	["justfile", HASH_FAMILY],
	["gemfile", HASH_FAMILY],
	["rakefile", HASH_FAMILY],
	[".gitignore", HASH_FAMILY],
	[".dockerignore", HASH_FAMILY],
	[".npmrc", HASH_FAMILY],
	[".env", HASH_FAMILY],
	[".bashrc", HASH_FAMILY],
	[".zshrc", HASH_FAMILY],
]);

const TEXT_DIRECTIVE_PATTERNS: readonly RegExp[] = [/^#!/, /^\/\*\s*globals?\s/, /^\/\*\s*(?:eslint|jshint|jslint)\b/];

const DIRECTIVE_PATTERNS: readonly RegExp[] = [
	/^-\*-/,
	/^(?:coding|encoding)[:=]/,
	/^eslint(?:-disable|-disable-line|-disable-next-line|-enable|-env)?\b/,
	/^(?:prettier-ignore|dprint-ignore|@format\b|@formatter:(?:off|on))/,
	/^(?:biome-ignore|oxlint-disable|deno-lint-ignore|deno-fmt-ignore|stylelint-(?:disable|enable))/,
	/^@ts-(?:ignore|expect-error|nocheck|check)\b/,
	/^@jsx(?:ImportSource)?\b/,
	/^(?:istanbul|c8|v8|node)\s+ignore\b/,
	/^SPDX-License-Identifier\b/,
	/^go:\w/,
	/^\+build\b/,
	/^nolint\b/,
	/^(?:noqa|nosec|NOSONAR)\b/,
	/^pragma\b/,
	/^type:\s*\S/,
	/^(?:mypy|pyright|pylint|ruff|flake8|isort|black|fmt|shellcheck|codeql|swiftlint|checkstyle|markdownlint|yamllint|hadolint|vale|editorconfig-checker):/i,
	/^(?:region|endregion)\b/,
	/^<auto-generated/,
	/^@generated\b/,
	/^Code generated\b.*\bDO NOT EDIT/,
];

const MARKER_PREFIX = /^(?:\/\/+|#+|--+|\/\*+|<!--|\*+)\s*/;

export function detectCommentSyntax(filePath: string): LanguageSyntax | null {
	const base = path.basename(filePath).toLowerCase();
	const byName = FILENAME_SYNTAX.get(base);
	if (byName) return byName;

	const extension = path.extname(base);
	if (extension) {
		const bySuffix = EXTENSION_SYNTAX.get(extension);
		if (bySuffix) return bySuffix;
	}
	if (base.startsWith("dockerfile") || base.startsWith("makefile")) return HASH_FAMILY;
	return null;
}

function isDirective(text: string): boolean {
	if (TEXT_DIRECTIVE_PATTERNS.some((pattern) => pattern.test(text))) return true;
	const body = text.replace(MARKER_PREFIX, "");
	return DIRECTIVE_PATTERNS.some((pattern) => pattern.test(body));
}

function hasBoundary(line: string, index: number): boolean {
	if (index === 0) return true;
	const previous = line[index - 1] ?? "";
	return /\s/.test(previous);
}

function startsWith(line: string, index: number, token: string): boolean {
	return line.startsWith(token, index);
}

type LineScan = {
	comment: string | null;
	openBlock: BlockToken | null;
	openDocstring: string | null;
};

function scanLine(line: string, syntax: LanguageSyntax): LineScan {
	let index = 0;
	let comment: string | null = null;

	while (index < line.length) {
		const character = line[index] ?? "";

		if (character === "\\") {
			index += 2;
			continue;
		}

		const docstring = syntax.docstringQuotes.find((quote) => startsWith(line, index, quote));
		if (docstring) {
			const end = line.indexOf(docstring, index + docstring.length);
			if (end === -1) return { comment, openBlock: null, openDocstring: docstring };
			index = end + docstring.length;
			continue;
		}

		if (syntax.quotes.includes(character)) {
			index += 1;
			while (index < line.length) {
				const inner = line[index] ?? "";
				if (inner === "\\") {
					index += 2;
					continue;
				}
				index += 1;
				if (inner === character) break;
			}
			continue;
		}

		const block = syntax.blockTokens.find((token) => startsWith(line, index, token[0]));
		if (block) {
			const end = line.indexOf(block[1], index + block[0].length);
			const text = end === -1 ? line.slice(index) : line.slice(index, end + block[1].length);
			comment ??= text.trim();
			if (end === -1) return { comment, openBlock: block, openDocstring: null };
			index = end + block[1].length;
			continue;
		}

		const lineToken = syntax.lineTokens.find(
			(token) => startsWith(line, index, token) && (!syntax.requireBoundary || hasBoundary(line, index)),
		);
		if (lineToken) {
			comment ??= line.slice(index).trim();
			return { comment, openBlock: null, openDocstring: null };
		}

		index += 1;
	}

	return { comment, openBlock: null, openDocstring: null };
}

function docstringOpener(line: string, quotes: readonly string[]): string | undefined {
	const body = line.trimStart().replace(/^[rbufRBUF]{0,2}/, "");
	return quotes.find((quote) => body.startsWith(quote));
}

function isDocstringPosition(lines: readonly string[], offset: number, wholeFile: boolean): boolean {
	for (let index = offset - 1; index >= 0; index -= 1) {
		const previous = lines[index] ?? "";
		if (previous.trim() === "") continue;
		return previous.trimEnd().endsWith(":");
	}
	return wholeFile;
}

export function findComments(
	filePath: string,
	lines: readonly string[],
	options: CommentScanOptions = {},
): CommentFinding[] {
	const syntax = detectCommentSyntax(filePath);
	if (!syntax) return [];

	const allowDirectives = options.allowDirectives !== false;
	const extraPatterns = options.allowPatterns ?? [];
	const knownLines = options.knownLines;
	const wholeFile = options.wholeFile === true;
	const findings: CommentFinding[] = [];

	const report = (offset: number, line: string, text: string): void => {
		if (extraPatterns.some((pattern) => pattern.test(text))) return;
		if (allowDirectives && isDirective(text)) return;
		if (knownLines?.has(line.trim())) return;
		findings.push({ line: offset + 1, text });
	};

	let openBlock: BlockToken | null = null;
	let openDocstring: string | null = null;

	lines.forEach((line, offset) => {
		if (openDocstring) {
			if (line.includes(openDocstring)) openDocstring = null;
			return;
		}
		if (openBlock) {
			if (line.includes(openBlock[1])) openBlock = null;
			return;
		}

		const quote = docstringOpener(line, syntax.docstringQuotes);
		if (quote && isDocstringPosition(lines, offset, wholeFile)) {
			const body = line.trimStart();
			const rest = body.slice(body.indexOf(quote) + quote.length);
			if (!rest.includes(quote)) openDocstring = quote;
			report(offset, line, line.trim());
			return;
		}

		const scan = scanLine(line, syntax);
		openBlock = scan.openBlock;
		openDocstring = scan.openDocstring;
		if (scan.comment) report(offset, line, scan.comment);
	});

	return findings;
}
